wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.revistas.usp.br/berev/oai&metadataFormat=oai_dc"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.revistas.usp.br/incid/oai&metadataFormat=oai_dc"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://revistas.ufpr.br/atoz/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.seer.ufal.br/index.php/cir/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://periodicos.furg.br/biblos/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://periodicos.ufmg.br/index.php/revistarbu/oai&metadataFormat=oai_dc"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www2.marilia.unesp.br/revistas/index.php/bjis/oai&metadataFormat=oai_dc"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.cajur.com.br/index.php/cajur/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://revista.acbsc.org.br/racb/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://revista.ibict.br/ciinf/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://portaldeperiodicos.eci.ufmg.br/index.php/pci/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://www.reciis.icict.fiocruz.br/index.php/reciis/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://rbbd.febab.org.br/rbbd/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://liinc.revista.ibict.br/index.php/liinc/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://www.seer.ufrgs.br/index.php/EmQuestao/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://abecin.org.br/portalderevistas/index.php/rebecin/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.periodicos.ufc.br/informacaoempauta/oai&metadataFormat=oai_dc"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://revista.ibict.br/fiinf/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://periodicos.ufca.edu.br/ojs/index.php/folhaderosto/oai&metadataFormat=oai_dc"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://revistas.ufrj.br/index.php/rca/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://portaldeperiodicos.eci.ufmg.br/index.php/moci/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.portalseer.ufba.br/index.php/revistaici/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://periodicos.ufsc.br/index.php/eb/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.uel.br/revistas/uel/index.php/informacao/oai&metadataFormat=rfc1807"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.uel.br/revistas/uel/index.php/infoprof/oai&metadataFormat=rfc1807"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.repositorios.ufpe.br/revistas/index.php/INF/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.repositorios.ufpe.br/revistas/index.php/IRIS/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.periodicoseletronicos.ufma.br/index.php/bibliomar/oai&metadataFormat=oai_dc"






wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://periodicos.ufpb.br/ojs2/index.php/biblio/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://periodicos.puc-campinas.edu.br/seer/index.php/transinfo/oai&metadataFormat=rfc1807"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://www.periodicos.ufpb.br/ojs2/index.php/ies/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://periodicos.unb.br/index.php/rici/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://periodicos.ufpb.br/ojs2/index.php/pgc/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=https://revistas.ufg.br/ci/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://periodicos.ufpb.br/ojs/index.php/itec/oai &metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://senacdoc.senac.br/index.php/senacdoc/oai&metadataFormat=nlm"
wget -O /dev/null -o /dev/null "http://35.239.2.201/rppbci/harvester.php?oai=http://inseer.ibict.br/ancib/index.php/tpbci/oai&metadataFormat=rfc1807"